package it.upo.reti2;

import java.util.Map;

/**
 * Sample usage of the Philips Hue API.
 *
 * @author <a href="mailto:luigi.derussis@uniupo.it">Luigi De Russis</a>
 * @version 1.0 (18/05/2017)
 */
public class hue {

    public static void main(String[] args) {
        // the URL of the Philips Hue bridge
        String baseURL = "http://172.30.1.138";

        // example username, generated by following https://www.developers.meethue.com/documentation/getting-started
        String username = "DeQdozx1Dv0GpOPfmN02HKdvmOcmXIe7e9aiCEAu";

        // base URL for lights
        String lightsURL = baseURL + "/api/" + username + "/lights/";

        // get the Hue lamps
        Map<String, ?> allLights = rest.get(lightsURL);

        // iterate over the Hue lamps, turn them on with the color loop effect
        //for (String light : allLights.keySet()) {
            String callURL = lightsURL + 2 + "/state";
            String body = "{ \"on\" : true, \"effect\" : \"colorloop\" }";
            rest.put(callURL, body, "application/json");
        //}

        // wait 10 seconds...
        for (int i = 0; i < 100; i++) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(100 - i);
        }

        // iterate over the Hue lamps and turn them off
        //for (String light : allLights.keySet()) {
            /*String*/ callURL = lightsURL + 2 + "/state";
            /*String*/ body = "{ \"on\" : false }";
            rest.put(callURL, body, "application/json");
        //}

    }
}
