package it.upo.reti2s;

import java.util.Map;

/**
 * Created by 20013051 on 29/05/2017.
 */
public class Hue {
    public static void main(String[] args) {
        // the URL of the Philips Hue bridge
        String baseURL = "http://172.30.1.138";
        // example username, generated by following https://www.developers.meethue.com/documentation/getting-started
        String username = "DeQdozx1Dv0GpOPfmN02HKdvmOcmXIe7e9aiCEAu";
        // base URL for lights
        String lightsURL = baseURL + "/api/" + username + "/lights/";
        // get the Hue lamps
        Map<String, ?> allLights = Rest.get(lightsURL);

        // iterate over the Hue lamps, turn them on with the color loop effect
        //for (String light : allLights.keySet()) {
        String callURL = lightsURL + 2 + "/state";
        String body = "{ \"on\" : true, \"effect\" : \"colorloop\" }";
        Rest.put(callURL, body, "application/json");
        //}

        // wait 10 seconds...
        for (int i = 0; i < 10; i++) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(10 - i);
        }

        // iterate over the Hue lamps and turn them off
        //for (String light : allLights.keySet()) {
            /*String*/ callURL = lightsURL + 2 + "/state";
            /*String*/ body = "{ \"on\" : false }";
        Rest.put(callURL, body, "application/json");
        //}

    }

    // colorLoop 1 hue
    public static void doColorLoop(String lamp){
        String body = "{ \"on\" : true, \"effect\" : \"colorloop\" }";
        Rest.put(lamp, body, "application/json");
        for (int i = 0; i < 30; i++) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(30 - i);
        }
        body = "{ \"on\" : false }";
        Rest.put(lamp, body, "application/json");
    }

    // turn on 1 hue
    public static void turnOn(String lamp){
        String body = "{ \"on\" : true}";
        Rest.put(lamp, body, "application/json");
    }

    //turn off 1 hue
    public static void turnOff(String lamp){
        String body = "{ \"on\" : false}";
        Rest.put(lamp, body, "application/json");
    }

    //turn on all hue
    public static void turnAllOn(){
        for (String light : allLights.keySet()) {
            callURL = lightsURL + light + "/state";
            body = "{ \"on\" : true }";
            Rest.put(callURL, body, "application/json");
        }
    }

    //turn off all hue
    public static void turnAllOff(String lamp){
        for (String light : allLights.keySet()) {
            callURL = lightsURL + light + "/state";
            body = "{ \"on\" : false }";
            Rest.put(callURL, body, "application/json");
        }
    }
}
